servers:
  - emoji: "🇺🇸"
    code: "us"
    name: "United States"
  - emoji: "🇬🇧"
    code: "uk"
    name: "United Kingdom"
  - emoji: "🇯🇵"
    code: "jp"
    name: "Japan"
  - emoji: "🇲🇽"
    code: "mexico"
    name: "Mexico"
  - emoji: "🇨🇦"
    code: "ca"
    name: "Canada"
  - emoji: "🇫🇮"
    code: "finland"
    name: "Finland"
  - emoji: "🇳🇿"
    code: "new_zealand"
    name: "New Zealand"
  - emoji: "🇬🇷"
    code: "greece"
    name: "Greece"
  - emoji: "🇦🇺"
    code: "australia"
    name: "Australia"
  - emoji: "🇮🇸"
    code: "iceland"
    name: "Iceland"
  - emoji: "🇵🇷"
    code: "puerto_rico"
    name: "Puerto Rico"
  - emoji: "🇮🇱"
    code: "israel"
    name: "Israel"
  - emoji: "🇷🇴"
    code: "romania"
    name: "Romania"
  - emoji: "🇰🇷"
    code: "south_korea"
    name: "South Korea"
  - emoji: "🇹🇼"
    code: "taiwan"
    name: "Taiwan"
